### ISSUE TITLE
Support for OpenApi 3.x oneOff, allOff, anyOff

### ISSUE THREAD

**Issue by mdaneri** [Badgerati/Pode#1168]
### Feature
Add support for OpenAPI 3.x oneOff, allOff, anyOff

### New Functions
`Merge-PodeOAProperty`

#### Parameters
- `-ParamsList`
Used to pipeline an object definition

- `-Type`
Define the type of validation between the objects
oneOf – validates the value against exactly one of the subschemas
allOf – validates the value against all the subschemas
anyOf – validates the value against any (one or more) of the subschemas

- `-ObjectDefinitions`
An array of object definitions that are used for independent validation but together compose a single object.

- `-DiscriminatorProperty`
If supplied, specifies the name of the property used to distinguish between different subtypes in a polymorphic schema in OpenAPI.
This string value represents the property in the payload that indicates which specific subtype schema should be applied.
It's essential in scenarios where an API endpoint handles data that conforms to one of several derived schemas from a common base schema.

- `-DiscriminatorMapping`
If supplied, define a mapping between the values of the discriminator property and the corresponding subtype schemas.
This parameter accepts a HashTable where each key-value pair maps a discriminator value to a specific subtype schema name.
It's used in conjunction with the -DiscriminatorProperty to provide complete discrimination logic in polymorphic scenarios.

### Example
```powershell 
Merge-PodeOAProperty  -Type OneOf -ObjectDefinitions @( 'Cat','Dog') -Discriminator "petType" |Add-PodeOAComponentSchema -Name 'Pets' 
```
```yaml
Pets : 
      oneOf : 
        - $ref : '#/components/schemas/Cat'
        - $ref : '#/components/schemas/Dog'
      discriminator : 
        propertyName : petType
```

```powershell  
Merge-PodeOAProperty  -Type AllOf -ObjectDefinitions 'Pet', (
            New-PodeOAStringProperty -Name 'huntingSkill' -Description 'The measured skill for hunting' -Enum @(  'clueless', 'lazy', 'adventurous', 'aggressive') | New-PodeOAObjectProperty
        ) | Add-PodeOAComponentSchema -Name 'Cat'
```

```yaml
Cat : 
      allOf : 
        - $ref : '#/components/schemas/Pet'
        - type : 
            - object
          properties : 
            huntingSkill : 
              type : 
                - string
              description : The measured skill for hunting
              enum : 
                - clueless
                - lazy
                - adventurous
                - aggressive
```
