### ISSUE TITLE
Missing Minimum and Maximum Property in OpenAPI Generation

### ISSUE THREAD

**Issue by mdaneri** [Badgerati/Pode#1365]
# Bug Report: Missing Minimum Property in OpenAPI Generation

### Describe the Bug

The `-Minimum` and `-Maximum` parameters are not converted to the appropriate properties in the OpenAPI specification when the value is 0.

### Steps To Reproduce

1. Run the following PowerShell command:

    ```powershell
    New-PodeOANumberProperty -Name 'Progress' -Description 'The async operation percentage progress' -Minimum 0 -Maximum 100
    ```

2. This generates the following OpenAPI YAML:

    ```yaml
    Progress: 
      type: number
      description: The async operation percentage progress
      maximum: 100
    ```

The `minimum` property is missing in the generated YAML.

### Expected Behavior

The generated OpenAPI YAML should include both the `minimum` and `maximum` properties when they are specified, even if the value is 0. The corrected YAML should look like this:

```yaml
Progress: 
  type: number
  description: The async operation percentage progress
  minimum: 0
  maximum: 100
```
