### ISSUE TITLE
Incorrect OpenAPI Schema Generation with `New-PodeOAObjectProperty` and `-NoProperties` Parameter

### ISSUE THREAD

**Issue by mdaneri** [Badgerati/Pode#1367]
### Describe the Bug

When using `New-PodeOAObjectProperty` with the `-AdditionalProperties` parameter and the `-NoProperties` switch, the generated OpenAPI schema incorrectly includes an empty `properties` array.

### Steps To Reproduce

1. Run the following PowerShell command:

    ```powershell
    New-PodeOAObjectProperty -Name 'HeaderFields' -AdditionalProperties (New-PodeOAStringProperty) -NoProperties | Add-PodeOAComponentSchema -Name 'test'
    ```

2. This generates the following incorrect OpenAPI YAML:

    ```yaml
    components: 
      schemas: 
        test: 
          type: object
          properties: []
          additionalProperties: 
            type: string
    ```

The `properties: []` array should not be present.

### Expected Behavior

The generated OpenAPI YAML should not include the `properties: []` array when the `-NoProperties` switch is used. The corrected YAML should look like this:

```yaml
components: 
  schemas: 
    test: 
      type: object
      additionalProperties: 
        type: string
```

### Fix

Ensure that the `properties` array is omitted from the generated OpenAPI schema when the `-NoProperties` switch is used.
