### ISSUE TITLE
OAuth2 with Reverse Proxy infront

### ISSUE THREAD

**Issue by RobinBeismann** [Badgerati/Pode#906]
### Question
I'm trying to create a Pode Service that shall serve as Forward Auth Proxy for the docker based reverse proxy called Traefik2.

Based on the docs I got that I need to set a redirect URL if running behind a reverse proxy otherwise Pode will deliver the local IP address which will (correctly) be rejected as redirect URL by Azure AD.

So I went ahead and configured the parameter `-RedirectUrl "https://auth.demo.system32.blog/oauth2/callback"` to have Pode sent this one as redirect to Azure AD.
In Azure AD I set the redirect URL "https://auth.demo.system32.blog/oauth2/callback" as reflected on the Pode Configuration.

However as soon as I open up the webpage, I get forwarded to Azure AD, authenticated and back to Pode where I receive a 404 for "http://auth.demo.system32.blog/oauth2/callback"
It is http:// and no longer https:// but I assume this is normal due to the SSL offloading at Traefik2.

Traefik is correctly forwarding the X-Forwarded-*. For reference, here is a container served with the same configuration that just dumps the HTTP Variables: https://whoami.demo.system32.blog/

Am I missing something? To me it looks like Pode stops listening on /oauth2/callback as soon as I specify it as redirect url, but I can't really figure out why after checking the code that is used.
I even tested modifying "Get-PodeOAuth2RedirectHost" to always apply the workaround for IIS/Heroku as it seems to behave the same using the headers.

My server.ps1 looks like this:
```
Import-Module /usr/local/share/powershell/Modules/Pode/Pode.psm1 -Force -ErrorAction Stop

Start-PodeServer {
    # http endpoint
    Add-PodeEndpoint -Address * -Port 80 -Protocol Http

    # Logging to console
    New-PodeLoggingMethod -Terminal | Enable-PodeRequestLogging
    New-PodeLoggingMethod -Terminal | Enable-PodeErrorLogging

    # Session Middleware
    Enable-PodeSessionMiddleware -Duration 120 -Extend

    # Generate Azure AD Scheme
    $scheme = New-PodeAuthAzureADScheme -ClientID '' -ClientSecret '' -Tenant '' -RedirectUrl "https://auth.demo.system32.blog/oauth2/callback"

    $scheme | Add-PodeAuth -Name 'Login' -FailureUrl '/login' -SuccessUrl '/' -ScriptBlock {
        param($user, $accessToken, $refreshToken, $response)

        # check if the user is valid

        return @{ User = $user }
    }

    # home page:
    # redirects to login page if not authenticated
    Add-PodeRoute -Method Get -Path '/' -Authentication Login -ScriptBlock {
        Write-PodeViewResponse -Path 'home' -Data @{ Username = $WebEvent.Auth.User.name }
    }

    # login - this will just redirect to azure
    # NOTE: you do not need the -Login switch
    Add-PodeRoute -Method Get -Path '/login' -Authentication Login

    # logout
    Add-PodeRoute -Method Post -Path '/logout' -Authentication Login -Logout
}
```

My docker-compose file looks like this and basically maps a local directory into the container while starting the actual Pode instance using a start-at-boot command:
```
version: '2'

services:
  podeauth:
    restart: always
    image: badgerati/pode:latest-alpine
    hostname: pode
    volumes:
      - ./pode:/usr/src/app/

    labels:
      # Traefik General
      - 'traefik.enable=true'
      - "traefik.docker.network=gateway"

      # Pode itself
      - 'traefik.http.routers.PodeAuth.rule=Host(`auth.demo.system32.blog`)'
      - 'traefik.http.routers.PodeAuth.entrypoints=websecure'
      - "traefik.http.routers.PodeAuth.service=PodeAuthService"
      - "traefik.http.services.PodeAuthService.loadBalancer.server.port=80"

      # Use Letsencrypt
      - "traefik.http.routers.PodeAuth.tls.certresolver=le_production"

    command: pwsh -c "cd /usr/src/app; ./server.ps1"
```
